---
title: "TEST - 1"
author: "sharat mishra"
date: "3 February 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
 tweets <- read.csv("C:/Users/Admin/Downloads/narendramodi_tweets.csv")
```

## 1

```{r}
## Dimension - lang,retweeted,
## Numerical - id,retweets_count,favorite_count, followers_count,friends_count,hashtag_count.
## Date - Created_at
## geo - location
## text - description,text,background_image_url,Source

summary(tweets)
class(tweets$id)
class(tweets$retweets_count)
class(tweets$favorite_count)
class(tweets$created_at)
class(tweets$text)
class(tweets$lang)
class(tweets$retweeted)
class(tweets$followers_count)
class(tweets$friends_count)
class(tweets$hashtags_count)
class(tweets$description)
class(tweets$location)



```


## 2

```{r}
library(ggplot2)
library(dplyr)
tweets$date <- as.Date(tweets$created_at,'%d-%m-%Y  %H:%M')
head(tweets)
tweets$day <-  format(tweets$date,'%d')
tweets_day = tweets %>% group_by(day) %>% summarise(count = n())
ggplot(tweets_day,aes(x=day,y=count)) +geom_bar(stat = 'identity',fill = "purple")+ coord_flip()

## 
```

## 3

```{r}
## A data visualization is a graphical representation of quantifiable data, usually by means of well-known chart, graph or map types. Although they can be created by hand, they can always be generated by applying automated methods on top of the data.
## It used when there is a huge amount of data.



##   An infographic is a graphical representation that combines one or more data visualizations with other non-data elements - such as graphics or text - to point out relationships, show a process or tell a story that cannot be automatically discerned from the data alone. An infographic requires the application of a creative process with some understanding of the underlying data and its context.
## It is used when there is a moderate amount of data.

```

## 4

```{r}

tweets$month_year <- format(tweets$date,'%m-%Y')
tweets_month_year = tweets %>% group_by(month_year) %>% summarise(count = sum(hashtags_count))
head(tweets_month_year)
ggplot(tweets_month_year,aes(x=month_year,y=count)) + geom_bar(stat = 'identity',fill = "purple") + coord_flip()


```

## 5

```{r}
odi.batting.analysis <- read.csv("C:/Users/Admin/Downloads/odi-batting-analysis.csv")
India <- filter(odi.batting.analysis,Country =='India' & Versus =='Australia')
india_vs_aus <- India %>% group_by(Player) %>% summarise(TotalRuns= sum(Runs))
india_vs_aus = india_vs_aus %>% arrange(-TotalRuns)
ggplot(head(india_vs_aus,5),aes(x=Player,y=TotalRuns, group=1)) + geom_line()

```

## 6

```{r}

sachin <- filter(odi.batting.analysis, Player == "Sachin R Tendulkar")
runs_country <- sachin %>% group_by(Versus) %>% summarise(Total = sum(Runs))
runs_country

ggplot(runs_country, aes(x = Versus, y = Total, )) + geom_bar(stat = "identity") + coord_flip()
```

## 7

```{r}
Runs_Score<-odi.batting.analysis%>% group_by(Player) %>%
summarise(TotalRuns=sum(Runs))%>%arrange(-TotalRuns)
Top_10<-head(Runs_Score,10)
Player_Name<-Top_10$Player
Top_Player<-filter(odi.batting.analysis,Player %in% Player_Name)
ggplot(Top_Player,aes(x=ScoreRate,y=Runs))+geom_point()+geom_smooth()+facet_wrap(~Player)
```





## 10

```{r}
century_miss <- filter(odi.batting.analysis,Runs>=90 & Runs <= 99)
top_missed_centuries <- century_miss %>% group_by(Player) %>% summarise(count=n())
top_missed_centuries = top_missed_centuries %>% arrange(-count)
ggplot(head(top_missed_centuries,5),aes(x=Player,y=count)) + geom_bar(stat='identity') + coord_flip()
```